name: Continuous Delivery (CD)
'on':
  push:
    branches:
    - main
    tags:
    - v*.*.*
    paths-ignore:
    - .github/**
    - docs/**
    - scripts/**
    - '**.md'
    - .gitignore
    - LICENSE
    - CODEOWNERS
    - deepdiffgo/**
env:
  DOCKER_REGISTRY_NAME: cloudbaristaorg
  GHCR_REGISTRY_NAME: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}
jobs:
  publish-container-image:
    name: Publish a container image
    if: github.repository_owner == 'z1fkoisp'
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v6
    - name: Extract metadata from Git reference and GitHub events
      id: meta
      uses: docker/metadata-action@v6
      with:
        images: '# image name for Docker Hub

          ${{env.DOCKER_REGISTRY_NAME}}/${{env.IMAGE_NAME}}

          # image name for GitHub Container Registry (GHCR)

          ghcr.io/${{env.GHCR_REGISTRY_NAME}}/${{env.IMAGE_NAME}}

          '
        tags: "# See `tags` input: https://github.com/docker/metadata-action?tab=readme-ov-file#tags-input\n\
          ## Tags for a push tag event\n# minimal (e.g., 1.2.3)\ntype=semver,enable=true,pattern={{version}}\n\
          # type=semver,pattern={{major}}.{{minor}}\n## Tags for a push branch event\n\
          # Tags to reflect the last commit of the active branch\ntype=edge,enable=true\n\
          ## Other types (currently the followings may be out of scope in this project)\n\
          ## Tags for a push branch event\n# minimal (short sha)\n# type=sha,enable=true,format=short\
          \            \n## Tags for a push or pull_request event\n# type=ref,event=branch\n\
          # type=ref,event=tag\n# type=ref,event=pr\n## Tags for a schedule event\
          \ - handlebars with timezone (e.g. 20200110-093000)\n# type=schedule,enable=true,pattern={{date\
          \ 'YYYYMMDD-hhmmss' tz='Asia/Tokyo'}}\n"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v4
    - name: Cache Docker layers
      uses: actions/cache@v5
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: '${{ runner.os }}-buildx-

          '
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and publish
      id: docker_build
      uses: docker/build-push-action@v7
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./
        file: ./Dockerfile
        target: prod
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
